name: Run DiscordBot from Private Repo

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-discordbot:
    runs-on: ubuntu-latest

    steps:
    - run: |
        git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/BILILICHENG/DanceVrushScoresDataPri.git private-repo

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        cd private-repo
        python -m pip install --upgrade pip > /dev/null 2>&1
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt > /dev/null 2>&1
        fi

    - run: |
        cd private-repo
        python discordbot.py > /dev/null 2>&1

    - run: |
        cd private-repo
        python uploadbot.py > /dev/null 2>&1

    - run: |
        cd private-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if git status --porcelain | grep .; then
          git add . > /dev/null 2>&1
          git commit -m "Auto update from GitHub Actions at $(date)" > /dev/null 2>&1
          git push origin main > /dev/null 2>&1
        fi

    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/BILILICHENG/save-test.git public-repo
        if [ -f private-repo/playerlist/online.txt ]; then
          if ! cmp -s private-repo/playerlist/online.txt public-repo/playerlist/online.txt 2>/dev/null; then
            cp private-repo/playerlist/online.txt public-repo/playerlist/online.txt
            cd public-repo
            git add playerlist/online.txt > /dev/null 2>&1
            git commit -m "Sync online.txt from private repo at $(date)" > /dev/null 2>&1
            git push origin master > /dev/null 2>&1
          fi
        fi

    - run: rm -rf private-repo public-repo
