name: Run DiscordBot from Private Repo

on:
  schedule:
    - cron: '0 * * * *'
    - cron: '20 * * * *'
    - cron: '40 * * * *'
  workflow_dispatch:

jobs:
  run-discordbot:
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repo securely
      run: |
        git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/BILILICHENG/DanceVrushScoresDataPri.git private-repo

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd private-repo
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run discordbot.py
      run: |
        cd private-repo
        python discordbot.py

    - name: Run uploadbot.py
      run: |
        cd private-repo
        python uploadbot.py

    - name: Commit and push any changes back to private repo
      run: |
        cd private-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto update from GitHub Actions at $(date)" || echo "No changes to commit"
        git push origin main

    - name: Push online.txt to public repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/BILILICHENG/save-test.git public-repo

        cp private-repo/playerlist/online.txt public-repo/playerlist/online.txt

        cd public-repo
        git add playerlist/online.txt

        if git diff --cached --quiet; then
          echo "No changes in online.txt, skipping commit."
        else
          git commit -m "Sync online.txt from private repo at $(date)"
          git push origin master
        fi
